Domain = "example.com"
ClientDir = "../kbclient"
Database = "mongodb://localhost/knowledgebase"

[[Server]]
Provider = "Engineering"

[[Server]]
Provider = "Community"

[[Server]]
Provider = "Help"